### ISSUE TITLE
I'm interested in code highlighting, but I can't display it correctly. I don't know what went wrong

### ISSUE THREAD

**Issue by SiriusXT** [antoniotejada/Trilium-SyntaxHighlightWidget#1]
I'm interested in code highlighting, but I can't display it correctly. I don't know what went wrong
![图片](https://user-images.githubusercontent.com/37627919/167072673-37829e45-5fd8-4afb-9c63-f191c2276d1d.png)
![图片](https://user-images.githubusercontent.com/37627919/167072698-1a70a70a-a13c-49ec-82f8-f0bd450a1371.png)
![图片](https://user-images.githubusercontent.com/37627919/167072712-bb09916e-addb-41ca-9511-d2ce451febad.png)
![图片](https://user-images.githubusercontent.com/37627919/167072854-26d2e6b7-a256-4c9d-8448-127f42926d7d.png)

**Comment by antoniotejada** [comment]
Looking at your screenshots (thanks!) I assume you pasted the text from `highlight.min.js` in a child script note, instead of attaching it to the script note as a file as per the [installation instructions](https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget#installation).

I'll clarify that on the `readme.md` anyway.

**Comment by antoniotejada** [comment]
Actually looks like both attaching as a file (three dot note menu -> import files -> uncheck all checkboxes -> choose files -> import) and pasting as a child code note work.

**Comment by SiriusXT** [comment]
Thank you very much. This script is great.
